<a href="https://colab.research.google.com/github/MllrJhssl/DC/blob/master/EJEMPLO_DE_RANDOM_FOREST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Cargar la biblioteca con el conjunto de datos del iris.
from sklearn.datasets import load_iris

In [0]:
# Cargar biblioteca de clasificador de bosque aleatorio de scikit
from sklearn.ensemble import RandomForestClassifier

In [0]:
import pandas as pd
import numpy as np
np.random.seed(0)

CARGAR DATOS

In [0]:
#Crea un objeto llamado iris con los datos del iris
iris = load_iris()
# Crear un marco de datos con las cuatro variables de características
df = pd.DataFrame(iris.data, columns=iris.feature_names)


In [0]:
# Ver las 5 filas superiores
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [0]:
# Agregar una nueva columna con los nombres de las especies, esto es lo que vamos a tratar de predecir
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

In [0]:
# Ver las 5 filas superiores
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species
0                5.1               3.5  ...               0.2   setosa
1                4.9               3.0  ...               0.2   setosa
2                4.7               3.2  ...               0.2   setosa
3                4.6               3.1  ...               0.2   setosa
4                5.0               3.6  ...               0.2   setosa

[5 rows x 5 columns]

CREAR ENTRENAMIENTO Y DATOS DE PRUEBA

In [0]:
# Cree una nueva columna que, para cada fila, genere un número aleatorio entre 0 y 1, y
# si ese valor es menor o igual a .75, entonces establece el valor de esa celda como Verdadero
# y falso de lo contrario. Esta es una manera rápida y sucia de asignar aleatoriamente algunas filas a
# ser utilizado como los datos de entrenamiento y algunos como los datos de prueba

df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75

In [0]:
# Ver las 5 filas superiores
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [0]:
# Cree dos nuevos marcos de datos, uno con las filas de entrenamiento, uno con las filas de prueba.
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [0]:
# Mostrar el número de observaciones para los marcos de datos de prueba y entrenamiento
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 118
Number of observations in the test data: 32


DATOS DE PREPROCESAMIENTO

In [0]:
# Crea una lista de los nombres de las columnas de características.
features = df.columns[:4]
# Ver características
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [0]:
# train ['especies'] contiene los nombres reales de las especies. Antes de que podamos usarlo,
# Necesitamos convertir cada nombre de especie en un dígito. Entonces, en este caso hay
# son tres especies, que se han codificado como 0, 1 o 2.
y = pd.factorize(train['species'])[0]
# Ver características
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

ENTRENAR EL CLASIFICAR DE Random Forest

In [0]:
# Crear un clasificador de bosque aleatorio. Por convención, clf significa 'Clasificador'
clf = RandomForestClassifier(n_jobs=2, random_state=0)
# Entrena al clasificador para tomar las características de entrenamiento y aprender cómo se relacionan
# a la formación y (la especie)
clf.fit(train[features], y)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

Hemos entrenado oficialmente nuestro clasificador de bosques al azar
Ahora vamos a jugar con eso. El propio modelo de clasificador se almacena en la clfvariable.

APLICAR CLASIFICADOR DE PRUEBA 

Si ha estado siguiendo, sabrá que solo entrenamos a nuestro clasificador en parte de los datos, dejando de lado el resto. Esta es, en mi humilde opinión, la parte más importante del aprendizaje automático. ¿Por qué? ¡Porque al omitir una parte de los datos, tenemos un conjunto de datos para probar la precisión de nuestro modelo!

In [0]:
# Aplique el clasificador que entrenamos a los datos de prueba (que, recuerde, nunca se ha visto antes)
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

arriba se ve que codificamos cada una de las tres especies de plantas como 0, 1 o 2. Lo que la lista de números anterior le muestra es qué especie predice nuestro modelo que cada planta se basa en la longitud del sépalo, el ancho del sépalo, la longitud del pétalo, y ancho de pétalo

In [0]:
# Ver las probabilidades pronosticadas de las primeras 10 observaciones
clf.predict_proba(test[features])[0:10]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

Hay tres especies de plantas, por lo tanto, [ 1. , 0. , 0. ]nos dice que el clasificador es cierto que la planta es la primera clase.

EVALUAR EL CLASIFICADOR

In [0]:
# Crear nombres reales en inglés para las plantas para cada clase de planta predicha
preds = iris.target_names[clf.predict(test[features])]

In [0]:
# Ver las especies PREDICTED para las primeras cinco observaciones
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [0]:
# Ver las especies PREDICTED para las primeras cinco observaciones
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]